<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>HTML (Lua - plt)</string>
    <key>uuid</key>
    <string>12bf63be-e8b1-4433-be37-2089ac067834</string>
    <key>scopeName</key>
    <string>text.html.plt</string>
    <key>fileTypes</key>
    <array>
      <string>plt</string>
      <string>html.plt</string>
    </array>
    <key>keyEquivalent</key>
    <string>^~H</string>
    <key>injections</key>
    <dict>
      <key>text.html.plt - (meta.embedded.line.plt | meta.embedded.inline.plt | comment)</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(^\s*)(?=#\s*--)</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.whitespace.comment.leading.plt</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?!\G)(\s*$\n)?</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.whitespace.comment.trailing.plt</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(^\s*)(?=#\s*(?!--))</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.whitespace.embedded.leading.plt</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?!\G)(\s*$\n)?</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.whitespace.embedded.trailing.plt</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#embedded_line</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#embedded_inline</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>text.html.basic</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.block.plt</string>
            <key>begin</key>
            <string>#\s*--\[\[</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.begin.plt</string>
              </dict>
            </dict>
            <key>end</key>
            <string>#\s*\]\]</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.end.plt</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.line.double-dash.plt</string>
            <key>begin</key>
            <string>#\s*--(?!\[\[)</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.begin.plt</string>
              </dict>
            </dict>
            <key>end</key>
            <string>$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.end.plt</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>embedded_line</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.embedded.line.plt</string>
            <key>contentName</key>
            <string>source.lua</string>
            <key>begin</key>
            <string>#</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.begin.plt</string>
              </dict>
            </dict>
            <key>end</key>
            <string>$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.end.plt</string>
              </dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>source.lua</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.lua</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>embedded_inline</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.embedded.inline.plt</string>
            <key>contentName</key>
            <string>source.lua</string>
            <key>begin</key>
            <string>\$\((?!\))</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.begin.plt</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)(?!\))</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.end.plt</string>
              </dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>source.lua</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.lua</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>
