<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>HTML (Lua - etlua)</string>
    <key>uuid</key>
    <string>ac3139e6-a9b0-4b0c-aaab-10d95ff79d97</string>
    <key>scopeName</key>
    <string>text.html.etlua</string>
    <key>fileTypes</key>
    <array>
      <string>etlua</string>
      <string>html.etlua</string>
    </array>
    <key>injections</key>
    <dict>
      <key>text.html.etlua - (meta.embedded.block.etlua | meta.embedded.line.etlua | comment)</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(^\s*)(?=&lt;%+#(?![^%]*%&gt;))</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.whitespace.comment.leading.etlua</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?!\G)(\s*$\n)?</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.whitespace.comment.trailing.etlua</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(^\s*)(?=&lt;%(?![^%]*%&gt;))</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.whitespace.embedded.leading.etlua</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?!\G)(\s*$\n)?</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.whitespace.embedded.trailing.etlua</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tags</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#tags</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>keyEquivalent</key>
    <string>^~H</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>text.html.basic</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.block.etlua</string>
            <key>begin</key>
            <string>&lt;%+#</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.begin.etlua</string>
              </dict>
            </dict>
            <key>end</key>
            <string>%&gt;</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.end.etlua</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>tags</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.embedded.block.etlua</string>
            <key>contentName</key>
            <string>source.lua</string>
            <key>begin</key>
            <string>&lt;%+(?!&gt;)[-=]?(?![^%]*%&gt;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.begin.etlua</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(-?%)&gt;</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.end.etlua</string>
              </dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>source.lua</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>comment.line.number-sign.etlua</string>
                <key>match</key>
                <string>(#).*?(?=-?%&gt;)</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.etlua</string>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>include</key>
                <string>source.lua</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.embedded.line.etlua</string>
            <key>contentName</key>
            <string>source.lua</string>
            <key>begin</key>
            <string>&lt;%+(?!&gt;)[-=]?</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.begin.etlua</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(-?%)&gt;</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.embedded.end.etlua</string>
              </dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>source.lua</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>comment.line.number-sign.etlua</string>
                <key>match</key>
                <string>(#).*?(?=-?%&gt;)</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.etlua</string>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>include</key>
                <string>source.lua</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>